In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset = pd.read_csv('../Data/Data.csv')

In [76]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [77]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [79]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [81]:
x_train = np.delete(x_train, 0, axis =1)
x_train

array([[0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [82]:
x_test = np.delete(x_test, 0, axis =1)
x_test

array([[1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [83]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [84]:
y_test

array([0, 1])

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [86]:
x_train

array([[0.0, 1.0, 38.77777777777778, -1.0781259408412422],
       [1.0, 0.0, 40.0, -0.0701316764163537],
       [0.0, 0.0, 44.0, 0.6335624327104549],
       [0.0, 1.0, 38.0, -0.3078661727429786],
       [0.0, 1.0, 27.0, -1.4204636155515817],
       [0.0, 0.0, 48.0, 1.2326533634535488],
       [1.0, 0.0, 50.0, 1.5749910381638883],
       [0.0, 0.0, 35.0, -0.5646194287757332]], dtype=object)

In [87]:
x_test

array([[1.0, 0.0, 30.0, -1.0],
       [0.0, 0.0, 37.0, 1.0]], dtype=object)