In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [4]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [5]:
# 편향 b도 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [8]:
optimizer = optim.SGD([W, b], lr=0.01)

In [9]:
nb_epochs = 1999

In [10]:
for epoch in range(nb_epochs + 1):
    hypothesis = W * x_train + b # H(x) 계산
    cost = torch.mean((hypothesis - y_train) ** 2) # cost 계산
    optimizer.zero_grad() # gradient를 0으로 초기화
    cost.backward() # 비용 함수를 미분하여 gradient 계산
    optimizer.step() # W와 b를 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch + 1, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    1/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  101/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  201/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  301/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  401/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  501/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  601/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  701/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  801/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  901/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1001/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1101/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1201/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1301/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1401/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1501/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1601/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1701/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1801/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1901/1999 W: 1.997, b: 0.008 Cost: 0.000008